#security:
#  oauth2:
#    client:
#      client-id: client
#      client-secret: clientsecret
#      scope: read,write
#      auto-approve-scopes: '.*'
#  user:
#    password: password
logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth2?characterEncoding=UTF-8
    username: root
    password: mhs83003255
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
#  context-path: /uaa